### ISSUE TITLE
 Error: Invalid or unsupported zip format. No END header found

### ISSUE THREAD

**Issue by system-failure-b8xy** [IvanikuV2/scratchvideo#4]
npm ERR! Error: Invalid or unsupported zip format. No END header found
npm ERR!     at readMainHeader (C:\MyStuff\scratchvideo-master\node_modules\adm-zip\zipFile.js:107:10)
npm ERR!     at new module.exports (C:\MyStuff\scratchvideo-master\node_modules\adm-zip\zipFile.js:19:3)
npm ERR!     at new module.exports (C:\MyStuff\scratchvideo-master\node_modules\adm-zip\adm-zip.js:20:11)
npm ERR!     at decompressZip (C:\MyStuff\scratchvideo-master\node_modules\ffmpeg-cli\lib\download.js:46:14)
npm ERR!     at C:\MyStuff\scratchvideo-master\node_modules\ffmpeg-cli\lib\download.js:78:75
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)

[2022-07-27T03_02_35_647Z-debug-0.log](https://github.com/IvanikuV2/scratchvideo/files/9194709/2022-07-27T03_02_35_647Z-debug-0.log)

**Comment by IvanikuV2** [comment]
Hey! I don't think that'll work since I had abandoned this project due to a really hard to overcome roadblock. I can try to retake it again, but I can't make any promise I will get it to work, so far [video support is almost finished](https://github.com/IvanikuV2/scratchvideo/issues/1) and [audio support is planned](https://github.com/IvanikuV2/scratchvideo/issues/2) (after video support gets added). Currently the thing that's stopping me from continuing this project is Scratch uses an obscure method to generate ID's for in-game assets. And even after lurking in [Scratch VM's code](https://github.com/LLK/scratch-vm) (the program that does all of the heavy lifting in Scratch's game engine) I couldn't find the algorithm that does this

When Scratch loads an SB3 file it makes sure that all assets follow this strict ID system, for example a Vector sprite would be something like `72dc56f9d552487990c960c99e626486.svg`, maybe I could start doing some tests with an in-house ID generator for scratchvideo. But as I mentioned before the debugging process in a project like this is really hard since Scratch is generally reluctant on saying why it didn't load a file.

If you or someone else looking at this issue have a better knowledge of how the scratch engine works feel free to reach me out on [GitHub](https://github.com/IvanikuV2) or [Matrix](https://matrix.to/#/@ivaniku:envs.net) and we can discuss this together. If you want to keep track of the project feel free to Watch it and check out these issues:

- [Video Support](https://github.com/IvanikuV2/scratchvideo/issues/1)
- [Audio Support](https://github.com/IvanikuV2/scratchvideo/issues/2)

**Comment by IvanikuV2** [comment]
I decided to move all of this into [one single issue](https://github.com/IvanikuV2/scratchvideo/issues/5), we're gettin' closer

**Comment by system-failure-b8xy** [comment]
Ok, take your time, it's fine!
Have a nice day!
